version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME:-youruser}/chatbot-backend:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME:-youruser}/chatbot-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE=http://backend:8003
    restart: unless-stopped

volumes:
  pgdata: {}
